<a href="https://colab.research.google.com/github/Ganapathi-tech/ganapathi-tech-Ganesh/blob/main/Naive_Bayes_TextC1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dfspam = pd.read_csv("spam.csv")

In [ ]:
dfspam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dfspam["Message"][2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [ ]:
dfspam["Category"].unique()

array(['ham', 'spam'], dtype=object)

In [ ]:
dfspam["Category"].value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
dic1={"ham" : 0, "spam" : 1}

In [ ]:
dfspam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dfspam["Category"].map(dic1)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

In [ ]:
pd.get_dummies(dfspam["Category"], drop_first = True)

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = "first")

In [ ]:
ary1 = ohe.fit_transform(dfspam[["Category"]]).toarray()

In [ ]:
ary1

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [ ]:
dfspam["Category"]

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object

In [ ]:
dfspam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dfspam["Spam"] = dfspam["Category"].apply( lambda x :  1 if x == "spam" else 0)

In [ ]:
var = lambda x :  1 if x == "spam" else 0

In [ ]:
var("ham")

0

In [ ]:
dfspam.head(10)

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

In [ ]:
dfspam[["Message"]].head()

Message
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dfspam[["Spam"]].head()

Spam
0     0
1     0
2     1
3     0
4     0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dfspam.Message, dfspam.Spam )

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)

(4179,)
(4179,)
(1393,)


In [ ]:
X_train.shape

(4179,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train.head()

2331     Long beach lor. Expected... U having dinner now?
3545    Lol ok ill try to send. Be warned Sprint is de...
3142                       Customer place i will call you
951            Awesome, lemme know whenever you're around
4639    Captain vijaykanth is doing comedy in captain ...
Name: Message, dtype: object

In [ ]:
X_test.head()

3972    Free video camera phones with Half Price line ...
3211    She said,'' do u mind if I go into the bedroom...
3262    Yup i'm still having coffee wif my frens... My...
5189    ree entry in 2 a weekly comp for a chance to w...
1505                           Oh my God. I'm almost home
Name: Message, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
v = CountVectorizer()

In [ ]:
X_train_count = v.fit_transform(X_train.values)

In [ ]:
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_count.shape

(4179, 7563)

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model = MultinomialNB()

In [ ]:
model.fit(X_train_count, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
X_test.head()

3972    Free video camera phones with Half Price line ...
3211    She said,'' do u mind if I go into the bedroom...
3262    Yup i'm still having coffee wif my frens... My...
5189    ree entry in 2 a weekly comp for a chance to w...
1505                           Oh my God. I'm almost home
Name: Message, dtype: object

In [ ]:
X_test_count = v.transform(X_test)

In [ ]:
y_test

3972    1
3211    0
3262    0
5189    1
1505    0
       ..
4622    0
3520    0
3780    1
2101    0
1190    0
Name: Spam, Length: 1393, dtype: int64

In [ ]:
X_test_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
model.score(X_test_count, y_test)

0.9899497487437185

In [ ]:
msg1 = ["Hello All, Lets meet over the weekend", 
        "Upto 20% discount on new arrivals, exclusive offer just for you.."]

In [ ]:
msg1_count = v.transform(msg1)

In [ ]:
msg1_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
model.predict(msg1_count)

array([0, 1])

PIPELINE 

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [ ]:
clf = Pipeline(
    [
     ("vectorizer", CountVectorizer()),
     ("nb",MultinomialNB())
    ]
  )

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)

(4179,)
(4179,)
(1393,)


In [ ]:
X_train.head()

2331     Long beach lor. Expected... U having dinner now?
3545    Lol ok ill try to send. Be warned Sprint is de...
3142                       Customer place i will call you
951            Awesome, lemme know whenever you're around
4639    Captain vijaykanth is doing comedy in captain ...
Name: Message, dtype: object

In [ ]:
X_test.head()

3972    Free video camera phones with Half Price line ...
3211    She said,'' do u mind if I go into the bedroom...
3262    Yup i'm still having coffee wif my frens... My...
5189    ree entry in 2 a weekly comp for a chance to w...
1505                           Oh my God. I'm almost home
Name: Message, dtype: object

In [ ]:
clf

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [ ]:
clf.score(X_test, y_test)

0.9899497487437185

In [ ]:
clf.predict(msg1)

array([0, 1])