<a href="https://colab.research.google.com/github/Ganapathi-tech/ganapathi-tech-Ganesh/blob/main/NaiveBayes1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
ship = pd.read_csv("titanic.csv")

In [ ]:
ship.head(10)

PassengerId  ... Survived
0            1  ...        0
1            2  ...        1
2            3  ...        1
3            4  ...        1
4            5  ...        0
5            6  ...        0
6            7  ...        0
7            8  ...        0
8            9  ...        1
9           10  ...        1

[10 rows x 12 columns]

In [ ]:
ship.shape

(891, 12)

In [ ]:
titanic = ship[["Gender", "Age", "Pclass", "Fare", "Survived"]]

In [ ]:
titanic

Gender   Age  Pclass     Fare  Survived
0      male  22.0       3   7.2500         0
1    female  38.0       1  71.2833         1
2    female  26.0       3   7.9250         1
3    female  35.0       1  53.1000         1
4      male  35.0       3   8.0500         0
..      ...   ...     ...      ...       ...
886    male  27.0       2  13.0000         0
887  female  19.0       1  30.0000         1
888  female   NaN       3  23.4500         0
889    male  26.0       1  30.0000         1
890    male  32.0       3   7.7500         0

[891 rows x 5 columns]

In [ ]:
gen = pd.get_dummies(titanic["Gender"], drop_first = True)

In [ ]:
gen.head()

male
0     1
1     0
2     0
3     0
4     1

In [ ]:
X = pd.concat([gen, titanic], axis = 1)

In [ ]:
titanic = titanic.drop(["Gender","Survived"], axis = 1)

In [ ]:
titanic

male   Age  Pclass     Fare
0       1  22.0       3   7.2500
1       0  38.0       1  71.2833
2       0  26.0       3   7.9250
3       0  35.0       1  53.1000
4       1  35.0       3   8.0500
..    ...   ...     ...      ...
886     1  27.0       2  13.0000
887     0  19.0       1  30.0000
888     0   NaN       3  23.4500
889     1  26.0       1  30.0000
890     1  32.0       3   7.7500

[891 rows x 4 columns]

In [ ]:
del X

In [ ]:
X = titanic

In [ ]:
X

male   Age  Pclass     Fare
0       1  22.0       3   7.2500
1       0  38.0       1  71.2833
2       0  26.0       3   7.9250
3       0  35.0       1  53.1000
4       1  35.0       3   8.0500
..    ...   ...     ...      ...
886     1  27.0       2  13.0000
887     0  19.0       1  30.0000
888     0   NaN       3  23.4500
889     1  26.0       1  30.0000
890     1  32.0       3   7.7500

[891 rows x 4 columns]

In [ ]:
y = ship[["Survived"]]

In [ ]:
X.head()

male   Age  Pclass     Fare
0     1  22.0       3   7.2500
1     0  38.0       1  71.2833
2     0  26.0       3   7.9250
3     0  35.0       1  53.1000
4     1  35.0       3   8.0500

In [ ]:
y.head()

Survived
0         0
1         1
2         1
3         1
4         0

In [ ]:
X.isnull().sum()

male        0
Age       177
Pclass      0
Fare        0
dtype: int64

In [ ]:
X.shape

(891, 4)

In [ ]:
y.isnull().sum()

Survived    0
dtype: int64

In [ ]:
var = X["Age"].mean()

In [ ]:
X.fillna(var, inplace = True)

In [ ]:
X.isnull().sum()

male      0
Age       0
Pclass    0
Fare      0
dtype: int64

In [ ]:
X.head()

male   Age  Pclass     Fare
0     1  22.0       3   7.2500
1     0  38.0       1  71.2833
2     0  26.0       3   7.9250
3     0  35.0       1  53.1000
4     1  35.0       3   8.0500

In [ ]:
X.dtypes

male        uint8
Age       float64
Pclass      int64
Fare      float64
dtype: object

In [ ]:
X["Age"] = X["Age"].astype("int")

In [ ]:
X["Age"]

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...    
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [ ]:
X.head()

male  Age  Pclass     Fare
0     1   22       3   7.2500
1     0   38       1  71.2833
2     0   26       3   7.9250
3     0   35       1  53.1000
4     1   35       3   8.0500

In [ ]:
X["Fare"].unique()

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
        31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,  18.    ,
         7.225 ,  26.    ,   8.0292,  35.5   ,  31.3875, 263.    ,
         7.8792,   7.8958,  27.7208, 146.5208,   7.75  ,  10.5   ,
        82.1708,  52.    ,   7.2292,  11.2417,   9.475 ,  21.    ,
        41.5792,  15.5   ,  21.6792,  17.8   ,  39.6875,   7.8   ,
        76.7292,  61.9792,  27.75  ,  46.9   ,  80.    ,  83.475 ,
        27.9   ,  15.2458,   8.1583,   8.6625,  73.5   ,  14.4542,
        56.4958,   7.65  ,  29.    ,  12.475 ,   9.    ,   9.5   ,
         7.7875,  47.1   ,  15.85  ,  34.375 ,  61.175 ,  20.575 ,
        34.6542,  63.3583,  23.    ,  77.2875,   8.6542,   7.775 ,
        24.15  ,   9.825 ,  14.4583, 247.5208,   7.1417,  22.3583,
         6.975 ,   7.05  ,  14.5   ,  15.0458,  26.2833,   9.2167,
        79.2   ,   6.75  ,  11.5   ,  36.75  ,   7.7958,  12.5

In [ ]:
X.isnull().sum()

male      0
Age       0
Pclass    0
Fare      0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.naive_bayes  import GaussianNB

In [ ]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.20)

In [ ]:
print(Xtrain.shape)
print(ytrain.shape)
print(Xtest.shape)
print(ytest.shape)

(712, 4)
(712, 1)
(179, 4)
(179, 1)


In [ ]:
GAmodel = GaussianNB()

In [ ]:
GAmodel.fit(Xtrain, ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
ypredict = GAmodel.predict(Xtest)

In [ ]:
ypredict

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1])

In [ ]:
GAmodel.score(Xtest, ytest)

0.8100558659217877

In [ ]:
GAmodel.predict([[1,29,3,7.5]])

array([0])

# WINE *DATASET*

In [ ]:
from sklearn  import datasets

In [ ]:
wine = datasets.load_wine()

In [ ]:
wine

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [ ]:
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
dir(wine)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [ ]:
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
wine.data.shape

(178, 13)

In [ ]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [ ]:
ary1 = np.random.randint(100,200,(4,6))

In [ ]:
ary1

array([[141, 113, 113, 151, 121, 171],
       [158, 193, 136, 105, 189, 167],
       [134, 125, 106, 117, 106, 154],
       [191, 115, 171, 171, 180, 113]])

In [ ]:
pd.DataFrame(ary1 , columns = ["A","B","C","D","E","F"])

A    B    C    D    E    F
0  141  113  113  151  121  171
1  158  193  136  105  189  167
2  134  125  106  117  106  154
3  191  115  171  171  180  113

In [ ]:
dfwine = pd.DataFrame(wine.data, columns = wine.feature_names)

In [ ]:
dfwine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [ ]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
dfwine["target"] = wine.target

In [ ]:
dfwine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [ ]:
dfwine.head()

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0    14.23        1.71  2.43  ...                          3.92   1065.0       0
1    13.20        1.78  2.14  ...                          3.40   1050.0       0
2    13.16        2.36  2.67  ...                          3.17   1185.0       0
3    14.37        1.95  2.50  ...                          3.45   1480.0       0
4    13.24        2.59  2.87  ...                          2.93    735.0       0

[5 rows x 14 columns]

In [ ]:
dfwine.to_csv("wine.csv")