<a href="https://colab.research.google.com/github/Ganapathi-tech/ganapathi-tech-Ganesh/blob/main/practice_cross_Validation_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
list1=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
a=pd.DataFrame(list1,columns=["Samples"])

In [ ]:
a

Samples
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
kf=KFold()
x=kf.split(a)
for i in x:
  print(i)

(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1]))
(array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3]))
(array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5]))
(array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7]))
(array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))


using cancer dataset

implement different types of cross validation technics

with decision tree algorithm






In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cancer=pd.read_csv("cancer.csv")

In [ ]:
cancer.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
cancer.shape

(569, 33)

In [ ]:
cancer.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [ ]:
cancer.drop("Unnamed: 32",axis=1,inplace=True)

In [ ]:
cancer

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

In [ ]:
cancer.shape

(569, 32)

In [ ]:
cancer.isna().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [ ]:
#Independent Variable
X=cancer.drop("diagnosis",axis=1)
X.shape

(569, 31)

In [ ]:
X

id  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0      842302        17.99  ...          0.4601                  0.11890
1      842517        20.57  ...          0.2750                  0.08902
2    84300903        19.69  ...          0.3613                  0.08758
3    84348301        11.42  ...          0.6638                  0.17300
4    84358402        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564    926424        21.56  ...          0.2060                  0.07115
565    926682        20.13  ...          0.2572                  0.06637
566    926954        16.60  ...          0.2218                  0.07820
567    927241        20.60  ...          0.4087                  0.12400
568     92751         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [ ]:
#Dependent Variable
y=cancer[["diagnosis"]]
y

diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

KFold Cross Validation

In [ ]:
kf=KFold(n_splits=5)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt=DecisionTreeClassifier()

In [ ]:
kf_score=cross_val_score(dt,X,y,cv=kf)


In [ ]:
kf_score

array([0.87719298, 0.92105263, 0.92982456, 0.92105263, 0.84070796])

In [ ]:
kf_score.mean()

0.8979661543238627

stratified KFold cross validation

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
dt2=DecisionTreeClassifier()

In [ ]:
dt2

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
sk=StratifiedKFold()

In [ ]:
sk_score=cross_val_score(dt2,X,y,cv=sk)

In [ ]:
print(sk_score)

[0.9122807  0.9122807  0.92105263 0.94736842 0.88495575]


In [ ]:
for i in sk_score:
  print(i)

0.9122807017543859
0.9122807017543859
0.9210526315789473
0.9473684210526315
0.8849557522123894


In [ ]:
sk_score.mean()

0.915587641670548

#loocv

leave one out cross Validation

In [ ]:
from sklearn.model_selection import LeaveOneOut

In [ ]:
l=LeaveOneOut()

In [ ]:
dt3=DecisionTreeClassifier()

In [ ]:
dt3

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
Loocv_score=cross_val_score(dt3,X,y,cv=l)

In [ ]:
Loocv_score

array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [ ]:
Loocv_score.shape

(569,)

In [ ]:
Loocv_score.mean()

0.929701230228471

yesterdays assignment: use one algorithm  with different cross validation technic on the adult dataset

here i can use KNN algorithm

In [ ]:

adult=pd.read_csv("adult.csv")

In [ ]:
adult

Unnamed: 0  age  fnlwgt  ...  capital-loss  hours-per-week  income
0               0   25  226802  ...             0              40   <=50K
1               1   38   89814  ...             0              50   <=50K
2               2   28  336951  ...             0              40    >50K
3               3   44  160323  ...             0              40    >50K
4               4   18  103497  ...             0              30   <=50K
...           ...  ...     ...  ...           ...             ...     ...
48837       48837   27  257302  ...             0              38   <=50K
48838       48838   40  154374  ...             0              40    >50K
48839       48839   58  151910  ...             0              40   <=50K
48840       48840   22  201490  ...             0              20   <=50K
48841       48841   52  287927  ...             0              40    >50K

[48842 rows x 10 columns]

In [ ]:
adult.drop("Unnamed: 0",axis=1,inplace=True)

In [ ]:
adult

age  fnlwgt  educational-num  ...  capital-loss  hours-per-week  income
0       25  226802                7  ...             0              40   <=50K
1       38   89814                9  ...             0              50   <=50K
2       28  336951               12  ...             0              40    >50K
3       44  160323               10  ...             0              40    >50K
4       18  103497               10  ...             0              30   <=50K
...    ...     ...              ...  ...           ...             ...     ...
48837   27  257302               12  ...             0              38   <=50K
48838   40  154374                9  ...             0              40    >50K
48839   58  151910                9  ...             0              40   <=50K
48840   22  201490                9  ...             0              20   <=50K
48841   52  287927                9  ...             0              40    >50K

[48842 rows x 9 columns]

In [ ]:
#Independent Variable 
X1=adult.drop("income",axis=1)

In [ ]:
X1.head()

age  fnlwgt  educational-num  ...  capital-gain  capital-loss  hours-per-week
0   25  226802                7  ...             0             0              40
1   38   89814                9  ...             0             0              50
2   28  336951               12  ...             0             0              40
3   44  160323               10  ...          7688             0              40
4   18  103497               10  ...             0             0              30

[5 rows x 8 columns]

In [ ]:

y1=adult[["income"]]

In [ ]:
y1.head()

income
0  <=50K
1  <=50K
2   >50K
3   >50K
4  <=50K

#KFold Cross Validation Technic 

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
kf1=KFold()

In [ ]:
knn=KNeighborsClassifier()

In [ ]:
kf1_score=cross_val_score(knn,X1,y1,cv=kf1)

In [ ]:
kf1_score

array([0.77356945, 0.77653803, 0.78429566, 0.7767199 , 0.77661753])

In [ ]:
for i in kf1_score:
  print(i)

0.7735694543965606
0.7765380284573651
0.7842956592956593
0.7767199017199017
0.7766175266175266


In [ ]:
kf1_score.mean()

0.7775481140974027

StractifiedKFold cross Validation

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
sk1=StratifiedKFold()

In [ ]:
knn1=KNeighborsClassifier()

In [ ]:
sk1_score=cross_val_score(knn1,X1,y1,cv=sk1)

In [ ]:
sk1_score

array([0.77203399, 0.77674276, 0.78286241, 0.7754914 , 0.78009828])

In [ ]:
for i in sk1_score:
  print(i)

0.7720339850547651
0.7767427577029379
0.7828624078624079
0.7754914004914005
0.7800982800982801


In [ ]:
sk1_score.mean()

0.7774457662419584

Loocv cross Validation

In [ ]:
from sklearn.model_selection import LeaveOneOut

In [ ]:
l1=LeaveOneOut()

In [ ]:
knn2=KNeighborsClassifier()

In [ ]:
#cross_val_score(knn2,X1,y1,cv=l1)